### PR TITLE
Add ability to set sampling rate

### PR DESCRIPTION
**Pull request by felixbarny**

### CODE REVIEW

**Comment by bripkens** [comment]
Hey @felixbarny,

congrats to your first contribution! Before considering this any further, could you please describe the use case behind it?

**Comment by felixbarny** [comment]
Hi Ben,

thx. Sure and sorry for not providing a description in the first place. At stagemonitor we have a configuration option which lets the user decide about the percentage of sampled spans. So they can configure that only 1% of the spans are actually sampled which means that they are reported to the backend.

The background is this issue: https://github.com/stagemonitor/stagemonitor/issues/341. The stagemonitor sampling rate setting does not work for ajax requests, as weasel hard codes the sampling decision to true: https://github.com/instana/weasel/blob/8a66020804b8dded9ed0247d51945b817349c2c4/lib/hooks/XMLHttpRequest.js#L185

After this change, I'm able to set the sampling rate to the configured one and inject it along with the init snippet into the html page.

**Comment by bripkens** [comment]
Thank you for explaining @felixbarny. This makes more sense now. Unfortunately, I am having a few issues with this change. First and foremost, we do not require sampling at Instana and therefore this is something that I would prefer not to ship to our customers. Secondly, I would not entrust end-user browsers with sampling decisions.

As a viable alternative (if you really need sampling), I would suggest to only embed the weasel tracking script for a percentage of the users. That is, evaluate the sampling decision on the server-side as part of the HTML document retrieval and conditionally include the tracking script. This has the additional benefit of sampling users (and not beacons). So one would get all the beacons for a certain user, thereby allowing better analysis.

**Comment by felixbarny** [comment]
> I would suggest to only embed the weasel tracking script for a percentage of the users

The problem is that there are two ways to integrate weasel into an application: 
1) I's a Java application and it is monitored by stagemonitor. In that case, weasel is injected automatically into the html
2) It's a web application which is not monitored by stagemonitor (for example a CMS application) and weasel is included by referencing the eum.js file of a standalone stagemonitor server.

In the second case, I can't just omit referencing the eum.js file as the reference is hardcoded into the CMS. However, I can modify the content of the eum.js dynamically (like when the sampling rate configuration is changed) as it is served by a stagemonitor standalone web application. So I could theoretically transmit a no-op script or set a meta tag to exclude all spans. But that comes with issues:

1) This completely breaks browser caching
2) I do want that all beacons are sent back, I just don't want to sample all spans. That's because stagemonitor keeps track of certain metrics like throughput and duration also for non sampled spans.

So the only real option for us is to add something that rarely changes (like the sampling rate) to the eum.js file.

> This has the additional benefit of sampling users (and not beacons). So one would get all the beacons for a certain user, thereby allowing better analysis.

That could also be added to my current implementation. But I'm a bit concerned about the implications of the empirical relevance. Probably it doesn't matter.

> Secondly, I would not entrust end-user browsers with sampling decisions.

Malicious users could just directly send fake beacons. The only remedy would be to add a token as a meta tag which expires after a certain amount of time. In stagemonitor, it's also possible to set a rate limit of sampled spans so it is possible to not sample a span, even if the client sends a header indicating that the span should be sampled. While this does not prevent that wrong data can be transmitted, it at least prevents that the backend can be flooded. 

> First and foremost, we do not require sampling at Instana and therefore this is something that I would prefer not to ship to our customers.

The change wouldn't have an effect to existing users as the default is to always sample.

Maybe a bit off topic, but I want to gain a better understanding about the goals of this project. So you won't merge anything into weasel unless you are actively using it for instana? Even optional features which don't affect instana users? The size of the minified script would also only very slightly increase with this change.

If you have come this far thanks a lot for your time ;)

**Comment by bripkens** [comment]
Hmm, so that sounds very much stagemonitor specific right now. Any chance you could just use the meta fields for this? Meta fields are available for all beacons so that way they are already propagated:

```
eum('meta', 'sampleRate', 0.5)
```

The server side would then evaluate the the field `m_sampleRate` on the server side and decide whether or not the beacon is only used for metrics or also used for tracing (this is how I understood your use case). This of course will require the server side to execute the `random` call, but that shouldn't be a problem.

> Maybe a bit off topic, but I want to gain a better understanding about the goals of this project. So you won't merge anything into weasel unless you are actively using it for instana? Even optional features which don't affect instana users? The size of the minified script would also only very slightly increase with this change.

The main goal of this project is to be totally open w.r.t. what we are doing on the websites we are monitoring. Customers must have the ability to inspect which objects we are touching and how we are manipulating them.

A secondary concern is to make this available as an open source project. In part, we are willing to accept open source contributions as long as they match our end-user monitoring vision. I am sorry if this is too vague, but that is the current strategy (we are still a small team so we don't have a lot of policies on this). Suppose you would be contributing automatic instrumentation of the `fetch` API or useful metrics (e.g. visually complete). This is something which I would definitely merge. 

In the end, the only way to have your proposed feature "integrated" into Weasel is probably some kind of simple plugin concept (something we won't be working on for the foreseeable future).

**Comment by felixbarny** [comment]
> Any chance you could just use the meta fields for this?

Unfortunately no, because my main concern is that the AJAX header `X-INSTANA-L` is hard coded to `1`. Adding a meta tag won't help here.

If your concern is the `sp` beacon parameter (`'sp': getSampledFlag(vars.sampleRate)`), we could omit it if it's `1` so nothing would change for those who don't wish to do sampling.

> Hmm, so that sounds very much stagemonitor specific right now.

I admit that some things might be specific to stagemonitor but I also think that especially the ability to embed eum into an application which is not monitored by stagemonitor, instana or whatever would be a valid use case. You even have documentation for just that: https://instana.atlassian.net/wiki/spaces/DOCS/pages/19365914/Web+End-User+Monitoring#WebEnd-UserMonitoring-InstallingtheJavaScriptAgent.

Also, sampling is a very common practice in tracing. I don't have sources but I've read that twitter only samples about 0.1% of all requests.

> In the end, the only way to have your proposed feature "integrated" into Weasel is probably some kind of simple plugin concept (something we won't be working on for the foreseeable future).

If my changes can't make it into weasel I'd probably have to maintain a fork in the mean time. 

Thx for explaining the goals. Seems reasonable.

**Pull request closed without merging**
